### PR TITLE
fix(sed): better support for converting sed patterns

### LINKED ISSUE #136: Regex support for forward slashes in sed
`shx v 0.3.0`:

I'm trying to build a cross-platform npm-script and I'm seeing an issue with directory path separators (unix `/` vs windows `\`). I thought I could use `sed` as a workaround, but hit the following issue:

```
❯ echo '{"js\\foo.js": "js\\foo-1234.js"}' | sed 's/\\/\//g'
{"js/foo.js": "js/foo-1234.js"}

❯ echo '{"js\\foo.js": "js\\foo-1234.js"}' | npx shx sed 's/\\/\//g'
.../node_modules/shx/lib/shx.js:105
        newArgs.push(new RegExp(regexString, regexFlags));
                     ^
SyntaxError: Invalid regular expression: /\/\/: \ at end of pattern
    at new RegExp (<anonymous>)
```

### PR DESCRIPTION
**Pull request by nfischer**
This PR does:

 1. Refactors sed-specific pattern-conversion logic. This logic converts
    a unix-style pattern (e.g., "s/foo/bar/") into the separate
    parameters expected by shell.sed() (e.g., new RegExp('foo'), 'bar').
    This builds the RegExp more carefully to avoid the issue with
    escaped slashes (as reported in #136).
 2. Explicitly checks for empty patterns and throws an error
    (previously, these would just silently fail conversion).
 3. Adds tests for the previous two cases.
 4. Refactors the sed tests to be more maintainable by saving file
    contents in test variables. No change in the logic of
    already-existing tests.

Fixes #136
Test: 'works with backslashes and forward slashes in pattern'
Test: 'does not work with empty regex strings'

### CODE REVIEW

File: src/shx.js [hunk 1]
```diff
@@ -11,6 +11,37 @@ objAssign.polyfill(); // modifies the global object
...
+    const escapedChar = '\\\\.'; // This may match an escaped slash (i.e., "\/")
+    const nonSlash = '[^/]';
+    const nonSlashSequence = `(?:${escapedChar}|${nonSlash})*`;
+    const sedPattern = `^s/(${nonSlashSequence})/(${nonSlashSequence})/(g?)$`;
+    const match = arg.match(new RegExp(sedPattern));
+    if (match && lookingForSubstString) {
+      const regexString = match[1].replace(/\\\//g, '/');
+      const replacement = match[2].replace(/\\\//g, '/').replace(/\\./g, '.');
+      const regexFlags = match[3];
+      if (!regexString) {
```
Comment (freitagbr) [inline src/shx.js]: Perhaps `regexString === ''` would be clearer here.

File: test/specs/cli.js [hunk 2]
```diff
@@ -317,6 +331,12 @@ describe('cli', () => {
         .equal('\nsomething\nsomething\n');
     });
 
+    it('does not work with empty regex strings', () => {
+      (() => {
+        cli('sed', 's//foo/g', testFileName1);
+      }).should.throw(Error);
```
Comment (freitagbr) [inline test/specs/cli.js]: I would check for the exact error message here, i.e. `.should.throw('Bad sed pattern (empty regex)')`.

File: src/shx.js (hunk 1 above)
Comment (nfischer) [reply src/shx.js]: done

File: test/specs/cli.js (hunk 2 above)
Comment (nfischer) [reply test/specs/cli.js]: done

**Comment by nfischer** [comment]
@freitagbr ptal

**Comment by freitagbr** [comment]
LGTM
